---
kind: Service
apiVersion: v1
metadata:
  name: iskstarter-service
  labels:
    app: iskstarter-web
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 4001
    protocol: TCP
  selector:
    app: iskstarter-web
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  labels:
    app: iskstarter-web
  name: iskstarter-web-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iskstarter-web
  template:
    metadata:
      labels:
        app: iskstarter-web
    spec:
      containers:
      - name: iskstarter-web-pod
        image: robbilie/iskstarter
        imagePullPolicy: Always
        ports:
        - containerPort: 4001
        volumeMounts:
        - name: config
          mountPath: "/etc/secrets"
          readOnly: true
        env:
        - name: APP_NAME
          value: "Web"
        - name: APP_PORT
          value: "4001"
        - name: HOST
          value: "isk-starter.com"
        - name: UA
          value: "Kubernetes ISKstarter Node.js Fetcher Test (Robert Schuh/Vincent Eneticum)"
        - name: MONGO_URL
          value: "mongodb://mongo-service:27017"
        - name: MONGO_DB
          value: "iskstarter"
        - name: XML_URL
          value: "https://api.eveonline.com"
        - name: CREST_URL
          value: "https://crest-tq.eveonline.com"
        - name: IMAGE_URL
          value: "https://imageserver.eveonline.com"
        - name: LOGIN_URL
          value: "https://login.eveonline.com"
        - name: ESI_URL
          value: "https://esi.tech.ccp.is/latest"
        - name: TAX
          value: "5"
        - name: CREST_CALLBACK
          value: "/login/callback/"
        - name: REDIS_HOST
          value: "redis-service"
        - name: REDIS_PORT
          value: "6379"
        - name: COOKIE_NAME
          value: "oauth.sid.v0001"
        - name: COOKIE_TTL
          value: "2592000000"
        - name: REFRESH_TOKEN
          value: "CqnO2MFh6jH4pKQVm2m7-cIOeBAn_PIjXQw-aBnauXU1"
        - name: CORPORATION_ID
          value: "98479854"
        readinessProbe:
          httpGet:
            path: /
            port: 4001
          initialDelaySeconds: 60
          timeoutSeconds: 60
        livenessProbe:
          httpGet:
            path: /
            port: 4001
          initialDelaySeconds: 60
          timeoutSeconds: 60
      volumes:
      - name: config
        secret:
          secretName: iskstarter-config
      nodeSelector:
        kubernetes.io/hostname: "sheliak"
      imagePullSecrets:
      - name: myregistrykey
